# get required pacakges
FIND_PACKAGE( FFMPEG REQUIRED )
FIND_PACKAGE( Cairo  REQUIRED )
FIND_PACKAGE( DevIL  REQUIRED )
FIND_LIBRARY( ZLIB_LIBRARY NAMES libz.a z zlib )

SET( LIBRARIES 
  ${FFMPEG_LIBRARIES}
  ${CAIRO_LIBRARIES}
  ${IL_LIBRARIES}
  ${ILU_LIBRARIES}
  ${ZLIB_LIBRARY}
)